"""empty message

Revision ID: 98ac2699e05b
Revises: 8c42e0f0dc6c
Create Date: 2024-03-16 23:42:09.227780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ac2699e05b'
down_revision = '8c42e0f0dc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
